app/src/main/java/rkr/simplekeyboard/inputmethod/keyboard/internal/KeyboardTextsTable.java, app/src/main/res/values-ur-rPK/strings.xml, app/src/main/res/xml-sw600dp/key_space_7kw.xml, app/src/main/res/xml-sw600dp/rows_urdu.xml, app/src/main/res/xml/kbd_urdu.xml, app/src/main/res/xml/key_space_5kw.xml, app/src/main/res/xml/key_styles_currency.xml, app/src/main/res/xml/keyboard_layout_set_urdu.xml, app/src/main/res/xml/method.xml, app/src/main/res/xml/rowkeys_urdu1.xml, app/src/main/res/xml/rowkeys_urdu2.xml, app/src/main/res/xml/rowkeys_urdu3.xml, app/src/main/res/xml/rows_urdu.xml
This PR adds a layout for Urdu.
Note: The file `KeyboardTextsTable.java` states that it shouldn't be edited manually. However, the tools required to generate that file require the AOSP code and are not present in Simple Keyboard. Therefore, I took the liberty of editing it manually anyway. (The count of texts at the end of the file is also not accurate, but they are stated in comments for informational purposes.)
=> Add keyboard layout for Urdu

app/src/main/java/rkr/simplekeyboard/inputmethod/keyboard/internal/KeyboardTextsTable.java
Fixes #91 
----
<a class="imgpatreon" href="https://www.patreon.com/emmanuelmess" target="_blank">
=> Fix german 'ß' being after '#'

app/src/main/res/values/donottranslate.xml, app/src/main/res/xml/kbd_alphabet.xml, app/src/main/res/xml/keyboard_layout_set_alphabet.xml, app/src/main/res/xml/row_alphabet4.xml, app/src/main/res/xml/rowkeys_alphabet0.xml, app/src/main/res/xml/rowkeys_alphabet1.xml, app/src/main/res/xml/rowkeys_alphabet2.xml, app/src/main/res/xml/rowkeys_alphabet3.xml, app/src/main/res/xml/rows_alphabet.xml
First pull request ever so bear with me if I've made any mistakes here!
Just adding an Alphabet ordered keyboard because my dad has some trouble with qwerty, and I've yet to find an actually decent one on the market.
Everything seems to work alright in the emulator for typing. It seems like there might be an existing bug that prevents any alternative English keyboard from showing up on the settings page.
I named the layout "alphabet", but I understand that, that might create an unfortunate pun for other parts of the application where you refer to alphabet as the letters on the keyboard (as opposed to numbers and special characters). So if that needs to change for this to be acceptable, let me know!
Thanks!
=> added configurations for an english alphabet layout

app/src/main/java/rkr/simplekeyboard/inputmethod/latin/LatinIME.java, app/src/main/java/rkr/simplekeyboard/inputmethod/latin/settings/Settings.java, app/src/main/java/rkr/simplekeyboard/inputmethod/latin/settings/SettingsValues.java, app/src/main/java/rkr/simplekeyboard/inputmethod/latin/utils/ResourceUtils.java, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_screen_advanced.xml
Also respects user defined keyboard background color.
Android 8 or newer required (SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR).
=> Enable white navigation bar for bright keyboard colors

app/src/main/java/rkr/simplekeyboard/inputmethod/keyboard/internal/KeyPreviewChoreographer.java
There was a bug in the key preview size after a dismiss animator was used. This is most noticeable when using a key with a single more key because the more key keyboard is supposed to line up with the key preview. When a dismiss animator is used (eg: a normal key press when hardware accelerated) the animation doesn't get reset. The animation apparently results in the y dimension of the view to be scaled to 0.94 based on my testing. Since the view is reused, when another key is pressed that preview shows up as slightly shorter than expected. I reset the y scale when reusing the key preview view, and I did the same for the x scale for good measure, even though I didn't see it changing.
=> reset the scale when reusing a key preview view

app/src/main/java/rkr/simplekeyboard/inputmethod/keyboard/internal/KeyboardTextsTable.java
reference: https://globalvoices.org/2020/09/11/are-romance-languages-becoming-more-gender-neutral/ and https://thesubmarine.it/2020/08/03/schwa-linguaggio-inclusivo-vera-gheno/
=> add "ə" to Italian layout

app/src/main/java/rkr/simplekeyboard/inputmethod/keyboard/Key.java, app/src/main/java/rkr/simplekeyboard/inputmethod/keyboard/KeyDetector.java, app/src/main/java/rkr/simplekeyboard/inputmethod/keyboard/internal/KeyboardRow.java, app/src/main/res/values/config-common.xml
Based on our discussion in 17862f16c345bfc6b76401bdc344af565d807d77, I fixed key hitboxes by allocating all of the vertical gap to the key above it and increasing the key hitbox padding limit. Since the hitboxes should be fixed, I also reverted `detectHitKey` to directly check if the touch point is in the key's hitbox, and I removed extra handling for overlapping keys since that can't happen anymore.
=> Fix key hitboxes

app/src/main/res/xml-sw600dp/keys_dvorak_123.xml, app/src/main/res/xml-sw600dp/rowkeys_dvorak3.xml, app/src/main/res/xml/kbd_dvorak.xml, app/src/main/res/xml/keys_dvorak_123.xml, app/src/main/res/xml/rowkeys_azerty2.xml, app/src/main/res/xml/rowkeys_azerty3.xml, app/src/main/res/xml/rowkeys_colemak1.xml, app/src/main/res/xml/rowkeys_colemak2.xml, app/src/main/res/xml/rowkeys_colemak3.xml, app/src/main/res/xml/rowkeys_dvorak1.xml, app/src/main/res/xml/rowkeys_dvorak2.xml, app/src/main/res/xml/rowkeys_dvorak3.xml
The azerty, colemak, and dvorak keyboards were missing the extra characters on the keys, so I added them. Also, the dvorak keyboard didn't show a separate number row when the setting was used, so I added support for that.
=> Add extra characters and a separate number row to some keyboards

app/src/main/res/xml-sw600dp/keys_dvorak_123.xml, app/src/main/res/xml/keys_dvorak_123.xml, app/src/main/res/xml/rowkeys_abc1.xml, app/src/main/res/xml/rowkeys_azerty1.xml, app/src/main/res/xml/rowkeys_colemak1.xml, app/src/main/res/xml/rowkeys_dvorak1.xml, app/src/main/res/xml/rowkeys_east_slavic1.xml, app/src/main/res/xml/rowkeys_greek1.xml, app/src/main/res/xml/rowkeys_qwerty1.xml, app/src/main/res/xml/rowkeys_qwertz1.xml
When the number row is shown and extra characters are not disabled, the top row of letters will also have extra characters now. This fixes #74, except for the suggestion for extra customization, but that probably should be a separate issue.
I used `_`, `\`, `|`, `=`, `[`, `]`, `<`, `>`, `{`, `}` for most of the keyboards, which matches Gboard, other than the the `%` and `_` flipped because SimpleKeyboard already used `%` on the second letter row where Gboard uses `_`. The East Slavic keyboard had a few extra keys, some of which already used some of the characters I was adding to the top row, so I also added `~`, `°`, `^`, `` ` ``, some of which are what Gboard used, but it has some redundant characters, so I added a couple that it didn't have (I'm not sure if there are better options, but …
=> Add extra characters to the top letter row

app/src/main/java/rkr/simplekeyboard/inputmethod/keyboard/internal/AlphabetShiftState.java, app/src/main/java/rkr/simplekeyboard/inputmethod/keyboard/internal/KeyboardState.java
You beat me to making a PR. This is the solution I came up with before seeing yours. The main difference is that I'm removing the `MANUAL_SHIFTED_FROM_AUTO` state. Basically, now it doesn't change to a manual shifted state internally when pressing the shift key on when it was already auto-shifted. It does seem a little weird that there are checks for the shift key state being pressing/chording on an auto-shift state, but I think that's better than internally saying that the state is manual shifted, but not actually update the keyboard to the manual shifted state. Assuming you agree, you might want to remove the `&& prevShiftMode != AUTOMATIC_SHIFT` change that you made in `setShifted`, as I don't think that's necessary. I'm requesting to add this to the branch for your PR since you're …
=> Don't mark the keyboard as manual shifted while pressing the shift key when it is already auto-shifted

app/src/main/java/rkr/simplekeyboard/inputmethod/keyboard/internal/KeyboardState.java
When sliding from shift to another key (not a more keys keyboard key) the keyboard is always changed to an unshifted state. In the case of a textCapCharacters field, selecting a character like `"` or `;` in a textCapWords field, or selecting a character like `"` after a `.` and a space in a textCapSentences field will result in an unshifted keyboard, even though auto-caps should have put it in a shifted state. If shift is pressed right after this, the first press does nothing. In a textCapCharacters field, the keyboard isn't re-shifted even after more characters are typed.
This fixes that problem. I'm not entirely sure what the `SWITCH_STATE_MOMENTARY_ALPHA_SHIFT` internal state was meant to solve, but it seems to only cause this bug, so I removed it.
I also removed a call to …
=> Allow auto-caps to work after sliding from shift

app/src/main/java/rkr/simplekeyboard/inputmethod/latin/LatinIME.java, app/src/main/java/rkr/simplekeyboard/inputmethod/latin/inputlogic/InputLogic.java
Some keyboard layouts don't utilize auto-capitalization functionality, presumably because the languages don't have the concept of upper/lower case letters. For these layouts auto-capitalization still functions to change the shift key into an `alphabetAutomaticShifted` state. To actually do a manual shift in this case requires shift to be pressed to unshift (making no difference in the other keys that are shown) and then pressed again to actually shift and show alternate keys. To prevent this issue, I disabled auto-capitalization for certain keyboard layouts.
The following layouts have this issue:
- bengali_akkhor
- georgian
- hindi
- khmer
- lao
- nepali_romanized
- nepali_traditional
- thai
- urdu
The following layouts don't have the problem because they don't even have a shift key, but …
=> Disable auto-capitalization for certain keyboard layouts

app/src/main/java/rkr/simplekeyboard/inputmethod/keyboard/internal/KeyboardTextsTable.java
It seems like Esperanto layout was modified by accident in commit b37c5edce7767d4a2d18c1afcc5ef0335bb81bae :
The original layout:
=> Fix Esperanto layout

app/src/main/java/rkr/simplekeyboard/inputmethod/latin/utils/LanguageOnSpacebarUtils.java
This fixes the displaying language on spacebar when multiple locales are enabled that use the same language and layout. For example, when English (US) QWERTY and English (UK) QWERTY are enabled and the US subtype is selected, "English (US)" should be shown on the spacebar, but if the UK subtype is disabled (and there is at least one other subtype enabled), it should just show "English".
I realized that in my changes in #274, I overlooked that `RichInputMethodManager::updateShortcutIme` called into `LanguageOnSpacebarUtils::onSubtypeChanged` and `LanguageOnSpacebarUtils::setEnabledSubtypes`, which left `sEnabledSubtypes` and `sIsSystemLanguageSameAsInputLanguage` always being the default value and broke this case.
`MainKeyboardView::onDrawKeyTopVisuals` only draws the language on the …
=> Fix displaying the language on the spacebar

app/src/main/res/values-night-v29/platform-theme.xml
This fixes an issue with the Input options dialog (long press the `,` key). In Android 9 if night mode is enabled, the dialog is themed dark. This doesn't match the system's input method picker dialog, which stays light even when night mode is on. I think it would make sense for these to match.
As some background info, the night mode implementation of Android 9 seems somewhat inconsistent along with not really being complete. There are 2 settings for a dark theme that I know of: `Display > Advanced > Device theme` and `System > Advanced > Developer options > Night mode`. On my phone, setting the Device theme changed things like the color of the Quick Settings menu (regardless of the Night mode setting). My phone was actually set to automatic Night mode, but the only things that I've …
=> Fix the dialog theme on Android 9

app/src/main/res/xml/method.xml
This fixes the issue where Gboard can't be disabled when Simple Keyboard is the only other keyboard that is enabled. Apparently a subtype needs to be explicitly defined for the keyboard.
=> Add a subtype for the keyboard

app/src/main/res/xml/rowkeys_georgian1.xml, app/src/main/res/xml/rowkeys_georgian2.xml, app/src/main/res/xml/rowkeys_georgian3.xml
Georgians do not use uppercase letters at all (although Georgian uppercase letters exist in Unicode).
=> Georgian keyboard: remove uppercase

app/src/main/res/xml/rowkeys_georgian1.xml, app/src/main/res/xml/rowkeys_georgian2.xml, app/src/main/res/xml/rowkeys_georgian3.xml
In GBoard v12:
**WAS** in Simple Keyboard:
**FIXED** in this pull request:
=> Georgian layout: add missing letters to `moreKeys`

app/src/main/java/rkr/simplekeyboard/inputmethod/keyboard/internal/KeyboardTextsTable.java
In Latvian layout in GBoard app Latvian letters with diacritics have higher priority than `latin:additionalMoreKeys`. (Similarly to French, German, Swedish languages etc.) This speeds up typing in these languages.
See the screenshots:
=> Latvian: set higher priority to frequent moreKeys

app/src/main/res/xml/method.xml
Hi,
it may not be of interest for many, but whenever the keyboard is included in an Android image as the only keyboard, this is needed to be able to enable the keyboard.
Otherwise, the option to enable it is greyed out in the Settings app.
I build Android for my phone and I noticed this including the keyboard instead of the AOSP one.
The keyboard language can be changed from the keyboard settings anyway.
=> Add subtype locale

app/src/main/java/rkr/simplekeyboard/inputmethod/latin/RichInputConnection.java
When changing the subtype by pressing the language switch key we need to track when the subtype is used to be able to keep the order of subtypes in order of most recently used.
Currently, the subtype is only marked as being used when committing text (and when finishing the input view). The subtype isn't marked as being used when sending a key press (entering numbers, backspacing, or moving the cursor when the cursor position is unknown), performing recapitalization, or moving the cursor position with swiping. Now those actions will also mark the subtype as being used.
=> Reset the subtype cycle order for more actions

app/src/main/java/rkr/simplekeyboard/inputmethod/keyboard/KeyboardId.java, app/src/main/java/rkr/simplekeyboard/inputmethod/keyboard/KeyboardLayoutSet.java, app/src/main/java/rkr/simplekeyboard/inputmethod/keyboard/KeyboardSwitcher.java, app/src/main/java/rkr/simplekeyboard/inputmethod/keyboard/internal/KeyboardBuilder.java, app/src/main/java/rkr/simplekeyboard/inputmethod/latin/settings/AppearanceSettingsFragment.java, app/src/main/java/rkr/simplekeyboard/inputmethod/latin/settings/Settings.java, app/src/main/java/rkr/simplekeyboard/inputmethod/latin/settings/SettingsValues.java, app/src/main/java/rkr/simplekeyboard/inputmethod/latin/utils/ResourceUtils.java, app/src/main/res/values/config-common.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/prefs_screen_appearance.xml
This adds the option to have extra padding at the bottom of the keyboard. This resolves #346.
I intentionally made this extra padding not clickable because the whole point is to shift the position of the keyboard, so I don't see a point in being able to click in this space, and depending on how large the offset is, registering clicks there seems like it would be unexpected for most users. We've had some debate on non-clickable spaces in the past, so if you disagree, I suppose I can change it.
I also only added support for portrait mode because I don't think there would be much point in landscape. In portrait mode, this offset can push the keyboard away from the navigation bar to avoid misclicks. Also, with phones having significantly smaller bezels than years ago, this can shift the …
=> Add a setting to add an offset to the bottom of the keyboard
